#!/usr/bin/env python3
"""
hostname.py — Generate the per-VM hostname first-boot script (Linux).

Emits a bash script that, on first boot, sets the machine hostname via
hostnamectl and keeps /etc/hostname and the 127.0.1.1 line of /etc/hosts in
sync. The value is validated here (generation time) and baked into the script
as a `cfg` block. The script does NOT reboot: the first-boot runner owns the
single reboot after all scripts succeed.

This tool only writes the .sh. Pack it into a config ISO with
pack_scripts_into_iso.py, which also writes the firstboot.manifest the runner
uses to find the disc:

  ./script-generators/linux-server/hostname.py --distro ubuntu -n web01 -o 10-hostname.sh
  ./pack_scripts_into_iso.py 10-hostname.sh 20-network.sh -o isos/web01-config.iso
"""

import argparse
import sys
from pathlib import Path

# These generators live two levels below the project root; put the root on the
# import path so `vmlib` resolves no matter the current working directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from vmlib.validate import validate_hostname_rfc  # noqa: E402

DISTROS = ("ubuntu", "debian", "rhel")
DEFAULT_SCRIPT_NAME = "10-hostname.sh"


def _sh_literal(value: str) -> str:
    """Render a Python string as a POSIX single-quoted shell literal (escape ')."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def _build_cfg_block(args: argparse.Namespace) -> str:
    lines = [
        f"distro={_sh_literal(args.distro)}",
        f"hostname={_sh_literal(args.hostname)}",
    ]
    return "\n".join(lines)


# The script writes progress to stdout (captured by the runner into
# /var/log/firstboot.log) and exits non-zero on failure (set -e), which makes
# the runner fail fast. It does NOT reboot -- the runner owns that.
_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
#
# Per-VM hostname first-boot configuration. Generated by hostname.py -- do not
# hand-edit. Run as root by the first-boot runner; sets the machine hostname,
# then exits. It does NOT reboot -- the runner owns the single reboot after all
# scripts succeed.
set -euo pipefail

# --- Config (baked in by the generator; values are pre-validated) ----------
{cfg_block}

echo "hostname: distro=$distro hostname=$hostname"

# --- Apply hostname --------------------------------------------------------
hostnamectl set-hostname "$hostname"
printf '%s\\n' "$hostname" > /etc/hostname

# Keep the loopback line in sync so `sudo` and local name resolution agree.
short=${{hostname%%.*}}
if grep -qE '^127\\.0\\.1\\.1[[:space:]]' /etc/hosts; then
    sed -i -E "s/^127\\.0\\.1\\.1[[:space:]].*/127.0.1.1\\t$hostname $short/" /etc/hosts
else
    printf '127.0.1.1\\t%s %s\\n' "$hostname" "$short" >> /etc/hosts
fi

echo "hostname: set to '$hostname' (no reboot -- runner owns it)."
"""


def render_hostname_script(args: argparse.Namespace) -> str:
    return _SCRIPT_TEMPLATE.format(cfg_block=_build_cfg_block(args))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hostname.py",
        description=(
            "Generate the per-VM hostname first-boot script (a .sh) for Linux.\n"
            "Pack it into a config ISO with pack_scripts_into_iso.py. The Linux\n"
            "first-boot runner runs it as root to set the machine hostname."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  %(prog)s --distro ubuntu -n web01 -o 10-hostname.sh\n"
            "  ./pack_scripts_into_iso.py 10-hostname.sh 20-network.sh "
            "-o isos/web01-config.iso"
        ),
    )
    parser.add_argument(
        "--distro", required=True, choices=DISTROS,
        help="Target Linux distribution.",
    )
    parser.add_argument(
        "-n", "--hostname", required=True, type=validate_hostname_rfc,
        metavar="HOSTNAME", help="VM hostname (RFC 1123).",
    )
    parser.add_argument(
        "-o", "--output", default=DEFAULT_SCRIPT_NAME,
        metavar="FILE",
        help=f"Output .sh path. Defaults to {DEFAULT_SCRIPT_NAME} in the current directory.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_hostname_script(args), encoding="utf-8")

    print(f"Script written to: {output_path}")
    print(f"  distro      = {args.distro}")
    print(f"  hostname    = {args.hostname}")
    print("\nNext: pack it into an ISO with")
    print(f"  ./pack_scripts_into_iso.py {output_path} -o isos/{args.hostname}-config.iso")


if __name__ == "__main__":
    main()
