#!/usr/bin/env python3
"""
network.py — Generate the per-VM network first-boot script (Linux).

Emits a bash script that, on first boot, configures the primary network
interface via systemd-networkd -- either a static IP (address, subnet prefix,
gateway, DNS) or DHCP -- by writing /etc/systemd/network/10-wired.network and
reloading networkd. The values are validated here (generation time) and baked
into the script as a `cfg` block. The script does NOT reboot: the first-boot
runner owns the single reboot after all scripts succeed. Hostname is configured
separately by hostname.py.

Assumes the golden image already uses systemd-networkd (it does not disable
NetworkManager/netplan/ifupdown). This tool only writes the .sh. Pack it into a
config ISO with pack_scripts_into_iso.py:

  # static
  ./script-generators/linux-server/network.py --distro ubuntu --ip 192.168.1.50 \\
      --prefix 24 --gateway 192.168.1.1 --dns1 192.168.1.10 -o 20-network.sh
  # dhcp
  ./script-generators/linux-server/network.py --distro debian --dhcp -o 20-network.sh
  ./pack_scripts_into_iso.py 10-hostname.sh 20-network.sh -o isos/web01-config.iso
"""

import argparse
import sys
from pathlib import Path

# These generators live two levels below the project root; put the root on the
# import path so `vmlib` resolves no matter the current working directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from vmlib.validate import validate_ipv4, validate_prefix  # noqa: E402

DISTROS = ("ubuntu", "debian", "rhel")
DEFAULT_SCRIPT_NAME = "20-network.sh"


def _sh_literal(value: str) -> str:
    """Render a Python string as a POSIX single-quoted shell literal (escape ')."""
    return "'" + str(value).replace("'", "'\\''") + "'"


def _build_cfg_block(args: argparse.Namespace) -> str:
    mode = "dhcp" if args.dhcp else "static"

    def lit(value) -> str:
        return _sh_literal("" if value is None else str(value))

    lines = [
        f"distro={_sh_literal(args.distro)}",
        f"mode={_sh_literal(mode)}",
        f"ip={lit(args.ip)}",
        f"prefix={lit(args.prefix)}",
        f"gateway={lit(args.gateway)}",
        f"dns1={lit(args.dns1)}",
        f"dns2={lit(args.dns2)}",
        f"dns_suffix={lit(args.dns_suffix)}",
    ]
    return "\n".join(lines)


# The script writes progress to stdout (captured by the runner into
# /var/log/firstboot.log) and exits non-zero on failure (set -e), which makes
# the runner fail fast. It does NOT reboot -- the runner owns that.
_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
#
# Per-VM network first-boot configuration. Generated by network.py -- do not
# hand-edit. Run as root by the first-boot runner; configures the primary
# interface for a static IP or DHCP via systemd-networkd, then exits. It does
# NOT reboot -- the runner owns the single reboot after all scripts succeed.
set -euo pipefail

# --- Config (baked in by the generator; values are pre-validated) ----------
{cfg_block}

echo "network: distro=$distro mode=$mode ip=$ip prefix=$prefix gateway=$gateway dns1=$dns1 dns2=$dns2 dns_suffix=$dns_suffix"

# --- Find the primary interface --------------------------------------------
# First physical (has a device link), non-loopback interface -- the NIC on a
# single-NIC VM. Avoids virtual interfaces (lo, veth, docker, bridges).
iface=""
for cand in /sys/class/net/*; do
    name=$(basename "$cand")
    [ "$name" = lo ] && continue
    [ -e "$cand/device" ] || continue
    iface=$name
    break
done
if [ -z "$iface" ]; then
    echo "network: ERROR: no physical network interface found" >&2
    exit 1
fi
echo "network: using interface $iface"

# --- Write the systemd-networkd unit ---------------------------------------
netfile=/etc/systemd/network/10-wired.network
: > "$netfile"
printf '%s\\n' "[Match]" "Name=$iface" "" "[Network]" >> "$netfile"
if [ "$mode" = dhcp ]; then
    printf '%s\\n' "DHCP=yes" >> "$netfile"
    echo "network: DHCP enabled on $iface"
else
    printf '%s\\n' "Address=$ip/$prefix" "Gateway=$gateway" >> "$netfile"
    echo "network: static $ip/$prefix via $gateway"
fi
# DNS (static override is also valid on top of DHCP); one DNS= line per server.
[ -n "$dns1" ] && printf '%s\\n' "DNS=$dns1" >> "$netfile"
[ -n "$dns2" ] && printf '%s\\n' "DNS=$dns2" >> "$netfile"
[ -n "$dns_suffix" ] && printf '%s\\n' "Domains=$dns_suffix" >> "$netfile"
chmod 0644 "$netfile"
echo "network: wrote $netfile"

# --- Apply -----------------------------------------------------------------
systemctl enable --now systemd-networkd
networkctl reload
echo "network: configuration applied (no reboot -- runner owns it)."
"""


def render_network_script(args: argparse.Namespace) -> str:
    return _SCRIPT_TEMPLATE.format(cfg_block=_build_cfg_block(args))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="network.py",
        description=(
            "Generate the per-VM network first-boot script (a .sh) for Linux.\n"
            "Configures the primary interface for a static IP or DHCP via\n"
            "systemd-networkd. Pack it into a config ISO with pack_scripts_into_iso.py."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  %(prog)s --distro ubuntu --ip 192.168.1.50 --prefix 24 "
            "--gateway 192.168.1.1 --dns1 192.168.1.10 -o 20-network.sh\n"
            "  %(prog)s --distro debian --dhcp -o 20-network.sh\n"
            "  %(prog)s --distro rhel --dhcp --dns1 192.168.1.10 "
            "--dns-suffix corp.example.com -o 20-network.sh\n"
            "  ./pack_scripts_into_iso.py 10-hostname.sh 20-network.sh "
            "-o isos/web01-config.iso"
        ),
    )
    parser.add_argument(
        "--distro", required=True, choices=DISTROS,
        help="Target Linux distribution.",
    )
    parser.add_argument(
        "--dhcp", action="store_true",
        help="Configure the interface via DHCP instead of a static IP. "
             "Makes --ip/--prefix/--gateway irrelevant and --dns1 optional.",
    )
    parser.add_argument(
        "--ip", type=validate_ipv4,
        metavar="ADDR", help="Static IPv4 address (dotted-quad). Required unless --dhcp.",
    )
    parser.add_argument(
        "--prefix", type=validate_prefix,
        metavar="LEN", help="Subnet prefix length (1-32). Required unless --dhcp.",
    )
    parser.add_argument(
        "--gateway", type=validate_ipv4,
        metavar="ADDR", help="Default gateway IPv4 address. Required unless --dhcp.",
    )
    parser.add_argument(
        "--dns1", default=None, type=validate_ipv4,
        metavar="ADDR", help="Primary DNS server IPv4 address. "
                             "Required for static; optional override for DHCP.",
    )
    parser.add_argument(
        "--dns2", default=None, type=validate_ipv4,
        metavar="ADDR", help="Secondary DNS server IPv4 address (optional).",
    )
    parser.add_argument(
        "--dns-suffix", default=None,
        metavar="SUFFIX", help="DNS search domain, e.g. corp.example.com (optional).",
    )
    parser.add_argument(
        "-o", "--output", default=DEFAULT_SCRIPT_NAME,
        metavar="FILE",
        help=f"Output .sh path. Defaults to {DEFAULT_SCRIPT_NAME} in the current directory.",
    )
    return parser


def _validate_args(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    """Enforce the static/DHCP argument contract argparse can't express directly."""
    if args.dhcp:
        conflicting = [
            name for name, val in (("--ip", args.ip), ("--prefix", args.prefix),
                                    ("--gateway", args.gateway))
            if val is not None
        ]
        if conflicting:
            parser.error(f"{', '.join(conflicting)} cannot be used with --dhcp.")
        if args.dns2 is not None and args.dns1 is None:
            parser.error("--dns2 requires --dns1.")
    else:
        missing = [
            name for name, val in (("--ip", args.ip), ("--prefix", args.prefix),
                                    ("--gateway", args.gateway), ("--dns1", args.dns1))
            if val is None
        ]
        if missing:
            parser.error(
                f"static mode requires {', '.join(missing)} (or pass --dhcp)."
            )


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    _validate_args(parser, args)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_network_script(args), encoding="utf-8")

    print(f"Script written to: {output_path}")
    print(f"  distro      = {args.distro}")
    if args.dhcp:
        print("  mode        = dhcp")
    else:
        print("  mode        = static")
        print(f"  ip/prefix   = {args.ip}/{args.prefix}")
        print(f"  gateway     = {args.gateway}")
    if args.dns1 is not None:
        print(f"  dns1        = {args.dns1}")
    if args.dns2 is not None:
        print(f"  dns2        = {args.dns2}")
    if args.dns_suffix is not None:
        print(f"  dns-suffix  = {args.dns_suffix}")
    print("\nNext: pack it into an ISO with")
    print(f"  ./pack_scripts_into_iso.py {output_path} -o isos/<hostname>-config.iso")


if __name__ == "__main__":
    main()
