#!/usr/bin/env bash
#
# firstboot-setup.sh -- Prepare a Linux golden image for per-VM first-boot config.
#
# The Linux analogue of base-vm-setup/windows-server/firstboot-sysprep.ps1. Run
# this ONCE on the golden image, as root, as the last step before you snapshot /
# export it. It:
#
#   1. Installs a generic first-boot RUNNER (/usr/local/sbin/firstboot-runner.sh)
#      and a systemd one-shot unit (firstboot.service) that invokes it on the
#      next boot of a deployed VM.
#   2. Ensures systemd-networkd is enabled (the per-VM network script assumes a
#      pure systemd-networkd image; it does not fight NetworkManager/netplan).
#   3. "Generalizes" the image (the sysprep-generalize analogue): resets the
#      machine-id, removes SSH host keys, clears logs and shell history, so each
#      deployed clone gets a fresh identity.
#
# On a deployed VM the runner locates the config disc by a firstboot.manifest at
# the root of a mounted ISO (the manifest isokit writes; see the pack-iso CLI),
# stages any payload files a v2 manifest lists, runs the scripts it lists -- in
# order, as root -- then owns the single reboot. Run is fail-fast: if any script
# exits non-zero, the runner logs it, writes /var/log/firstboot-error.log, and
# does NOT reboot.
#
# The config disc is produced by the pack-iso CLI (isokit) from per-VM scripts
# generated by configgen (gen-hostname / gen-network).
#
# Usage:
#   sudo ./firstboot-setup.sh                 # generalize, then power off
#   sudo ./firstboot-setup.sh --no-shutdown   # leave the VM running
set -euo pipefail

SHUTDOWN=1

usage() {
    echo "Usage: $0 [--no-shutdown]" >&2
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --no-shutdown) SHUTDOWN=0; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root." >&2
    exit 1
fi

# Informational only -- nothing below branches on the distro.
DISTRO="$( . /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-$ID}" )"
DISTRO="${DISTRO:-unknown}"

echo "===== firstboot-setup ($DISTRO) ====="

RUNNER=/usr/local/sbin/firstboot-runner.sh
UNIT=/etc/systemd/system/firstboot.service

# ---------------------------------------------------------------------------
# 1. Install the first-boot runner
# ---------------------------------------------------------------------------
# The runner is a real sibling file (single source of truth, testable against
# a fake disc dir) rather than an embedded heredoc. Copy the whole
# linux-server/ folder to the VM, not just this script.

echo "Installing runner: $RUNNER"
runner_src="$(cd "$(dirname "$0")" && pwd)/firstboot-runner.sh"
[ -f "$runner_src" ] || { echo "ERROR: firstboot-runner.sh not found next to this script ($runner_src). Copy the whole linux-server/ folder to the VM." >&2; exit 1; }
grep -q 'FIRSTBOOT-RUNNER-MARKER' "$runner_src" || { echo "ERROR: $runner_src does not look like the first-boot runner (marker missing)." >&2; exit 1; }
install -m 0755 "$runner_src" "$RUNNER"

# The runner parses firstboot.manifest with python3 -- surface a missing
# interpreter at image-build time, not on first boot of a deployed clone.
command -v python3 >/dev/null 2>&1 || \
    echo "WARN: python3 not found -- the first-boot runner requires it to parse firstboot.manifest."

# ---------------------------------------------------------------------------
# 2. Install the systemd one-shot unit
# ---------------------------------------------------------------------------
echo "Installing unit: $UNIT"
cat > "$UNIT" <<UNIT
[Unit]
Description=First-boot per-VM configuration runner
After=network-pre.target systemd-networkd.service local-fs.target
Wants=network-pre.target
# Skip once the runner has succeeded (it also disables itself).
ConditionPathExists=!/var/lib/firstboot/done

[Service]
Type=oneshot
ExecStart=$RUNNER
RemainAfterExit=no
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable firstboot.service
echo "Enabled firstboot.service (runs on next boot)."

# ---------------------------------------------------------------------------
# 3. Ensure systemd-networkd (+ resolved for DNS=) are enabled
# ---------------------------------------------------------------------------
echo "Enabling systemd-networkd ..."
systemctl enable systemd-networkd >/dev/null 2>&1 || \
    echo "WARN: could not enable systemd-networkd -- ensure the base image provides it."
# systemd-resolved makes the .network DNS= directives take effect via resolv.conf.
systemctl enable systemd-resolved >/dev/null 2>&1 || \
    echo "WARN: systemd-resolved not enabled -- DNS= in .network may not apply."

# ---------------------------------------------------------------------------
# 4. Generalize the image (run last, just before snapshot/export)
# ---------------------------------------------------------------------------
echo "Generalizing image ..."

# Fresh machine-id per clone (duplicate IDs break systemd-networkd DHCP/identity).
: > /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id 2>/dev/null || true

# SSH host keys regenerate on next boot (avoids cloned hosts sharing keys).
rm -f /etc/ssh/ssh_host_* 2>/dev/null || true

# cloud-init (if present) -- reset so it re-runs cleanly on the clone.
if command -v cloud-init >/dev/null 2>&1; then
    cloud-init clean --logs >/dev/null 2>&1 || true
fi

# Clear logs and shell history.
find /var/log -type f -exec truncate -s 0 {} + 2>/dev/null || true
rm -f /root/.bash_history 2>/dev/null || true
for home in /home/*; do
    [ -d "$home" ] && rm -f "$home/.bash_history" 2>/dev/null || true
done

echo "===== firstboot-setup complete ($DISTRO) ====="
echo "Runner : $RUNNER"
echo "Unit   : $UNIT (enabled)"
echo "Next   : snapshot/export this image as your golden image."

if [ "$SHUTDOWN" -eq 1 ]; then
    echo "Shutting down ..."
    sync
    systemctl poweroff
else
    echo "Leaving VM running (--no-shutdown). Power it off when ready."
fi
