#!/usr/bin/env bash
#
# firstboot-setup.sh -- Prepare a Linux golden image for per-VM first-boot config.
#
# The Linux analogue of base-vm-setup/windows-server/firstboot-sysprep.ps1. Run
# this ONCE on the golden image, as root, as the last step before you snapshot /
# export it. It:
#
#   1. Installs a generic first-boot RUNNER (/usr/local/sbin/firstboot-runner.sh)
#      and a systemd one-shot unit (firstboot.service) that invokes it on the
#      next boot of a deployed VM.
#   2. Ensures systemd-networkd is enabled (the per-VM network script assumes a
#      pure systemd-networkd image; it does not fight NetworkManager/netplan).
#   3. "Generalizes" the image (the sysprep-generalize analogue): resets the
#      machine-id, removes SSH host keys, clears logs and shell history, so each
#      deployed clone gets a fresh identity.
#
# On a deployed VM the runner locates the config disc by a firstboot.manifest at
# the root of a mounted ISO (the same manifest pack_scripts_into_iso.py writes),
# runs the scripts it lists -- in order, as root -- then owns the single reboot.
# Run is fail-fast: if any script exits non-zero, the runner logs it, writes
# /var/log/firstboot-error.log, and does NOT reboot.
#
# The config disc is produced by pack_scripts_into_iso.py from per-VM scripts
# generated by script-generators/linux-server/hostname.py and network.py.
#
# Usage:
#   sudo ./firstboot-setup.sh                 # generalize, then power off
#   sudo ./firstboot-setup.sh --no-shutdown   # leave the VM running
set -euo pipefail

SHUTDOWN=1

usage() {
    echo "Usage: $0 [--no-shutdown]" >&2
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --no-shutdown) SHUTDOWN=0; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root." >&2
    exit 1
fi

# Informational only -- nothing below branches on the distro.
DISTRO="$( . /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-$ID}" )"
DISTRO="${DISTRO:-unknown}"

echo "===== firstboot-setup ($DISTRO) ====="

RUNNER=/usr/local/sbin/firstboot-runner.sh
UNIT=/etc/systemd/system/firstboot.service

# ---------------------------------------------------------------------------
# 1. Install the first-boot runner
# ---------------------------------------------------------------------------
# Heredoc is single-quoted ('RUNNER') so NOTHING below is expanded now -- the
# script is written verbatim and runs on the deployed VM's first boot.

echo "Installing runner: $RUNNER"
cat > "$RUNNER" <<'RUNNER'
#!/usr/bin/env bash
#
# First-boot config runner. Installed by firstboot-setup.sh and invoked once by
# firstboot.service on a deployed VM. Locates the config disc by its
# firstboot.manifest, runs the listed scripts in order as root, and owns the
# single reboot. Fail-fast: the first non-zero exit aborts the run (no reboot).
# Produces no console output (runs before any login); progress and errors go to
# /var/log/firstboot.log (fatal errors additionally to /var/log/firstboot-error.log).

# NB: intentionally no `set -e` -- failures are handled explicitly so the runner
# controls whether a reboot happens.
set -uo pipefail

LOG=/var/log/firstboot.log
ERRLOG=/var/log/firstboot-error.log
SENTINEL=/var/lib/firstboot/done
MOUNTPOINT=/run/firstboot-cd
WORKDIR=/run/firstboot-scripts
MANIFEST_NAME=firstboot.manifest

log()  { printf '%s  %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" >> "$LOG"; }
fail() {
    log "ERROR: $1"
    printf '%s  ERROR: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1" > "$ERRLOG"
    log "Machine NOT rebooted. See $ERRLOG."
    umount "$MOUNTPOINT" 2>/dev/null || true
    exit 1
}

mkdir -p "$(dirname "$SENTINEL")"
log "===== firstboot runner starting (as $(id -un) on $(hostname)) ====="

# -- 1. Locate the config disc by its firstboot.manifest marker --------------
manifest=""
mounted_dev=""
mkdir -p "$MOUNTPOINT"
for dev in /dev/sr* /dev/cdrom; do
    [ -b "$dev" ] || continue
    umount "$MOUNTPOINT" 2>/dev/null || true
    log "Scanning $dev for $MANIFEST_NAME ..."
    if mount -o ro "$dev" "$MOUNTPOINT" 2>/dev/null; then
        if [ -f "$MOUNTPOINT/$MANIFEST_NAME" ]; then
            manifest="$MOUNTPOINT/$MANIFEST_NAME"
            mounted_dev="$dev"
            break
        fi
        umount "$MOUNTPOINT" 2>/dev/null || true
    fi
done
[ -n "$manifest" ] || fail "No config disc found. Ensure $MANIFEST_NAME is at the root of a mounted ISO."
log "Config disc: $mounted_dev (manifest: $manifest)"

# -- 2. Parse the manifest into an ordered list of scripts -------------------
# The manifest is JSON written by pack_scripts_into_iso.py (indent=2), so each
# array entry is on its own line. Pull the lines inside the "scripts": [ ... ]
# block (dropping the bracket lines) and extract the quoted filenames in order.
mapfile -t scripts < <(
    sed -n '/"scripts"[[:space:]]*:[[:space:]]*\[/,/\]/{/\[/d;/\]/d;p}' "$manifest" \
        | grep -oE '"[^"]+"' | tr -d '"'
)
[ "${#scripts[@]}" -gt 0 ] || fail "Manifest '$manifest' has no non-empty 'scripts' list."
log "${#scripts[@]} script(s) in order: ${scripts[*]}"

# -- 3. Stage scripts locally and run each in order --------------------------
rm -rf "$WORKDIR"; mkdir -p "$WORKDIR"
for name in "${scripts[@]}"; do
    src="$MOUNTPOINT/$name"
    [ -f "$src" ] || fail "Manifest lists '$name' but it is not present on the disc ($src)."
    dst="$WORKDIR/$name"
    cp -f "$src" "$dst"
    chmod +x "$dst"

    log "----- Running '$name' -----"
    if bash "$dst" >"$dst.out" 2>"$dst.err"; then
        while IFS= read -r line; do [ -n "$line" ] && log "  [out] $line"; done < "$dst.out"
        log "----- '$name' completed (exit 0) -----"
    else
        rc=$?
        while IFS= read -r line; do [ -n "$line" ] && log "  [out] $line"; done < "$dst.out"
        while IFS= read -r line; do [ -n "$line" ] && log "  [err] $line"; done < "$dst.err"
        fail "Script '$name' exited with code $rc. Aborting first-boot run -- NOT rebooting."
    fi
done
log "All ${#scripts[@]} script(s) completed successfully."

# -- 4. Finalize: mark done, disable self, reboot once -----------------------
# Linux applies hostname/network live, so no Windows-style second "finalize"
# reboot is needed -- one reboot lands the VM in a clean steady state.
umount "$MOUNTPOINT" 2>/dev/null || true
touch "$SENTINEL"                                  # ConditionPathExists guard
systemctl disable firstboot.service >/dev/null 2>&1 || true
log "Configuration complete -- rebooting."
sync
systemctl reboot
RUNNER
chmod 0755 "$RUNNER"

# ---------------------------------------------------------------------------
# 2. Install the systemd one-shot unit
# ---------------------------------------------------------------------------
echo "Installing unit: $UNIT"
cat > "$UNIT" <<UNIT
[Unit]
Description=First-boot per-VM configuration runner
After=network-pre.target systemd-networkd.service local-fs.target
Wants=network-pre.target
# Skip once the runner has succeeded (it also disables itself).
ConditionPathExists=!/var/lib/firstboot/done

[Service]
Type=oneshot
ExecStart=$RUNNER
RemainAfterExit=no
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable firstboot.service
echo "Enabled firstboot.service (runs on next boot)."

# ---------------------------------------------------------------------------
# 3. Ensure systemd-networkd (+ resolved for DNS=) are enabled
# ---------------------------------------------------------------------------
echo "Enabling systemd-networkd ..."
systemctl enable systemd-networkd >/dev/null 2>&1 || \
    echo "WARN: could not enable systemd-networkd -- ensure the base image provides it."
# systemd-resolved makes the .network DNS= directives take effect via resolv.conf.
systemctl enable systemd-resolved >/dev/null 2>&1 || \
    echo "WARN: systemd-resolved not enabled -- DNS= in .network may not apply."

# ---------------------------------------------------------------------------
# 4. Generalize the image (run last, just before snapshot/export)
# ---------------------------------------------------------------------------
echo "Generalizing image ..."

# Fresh machine-id per clone (duplicate IDs break systemd-networkd DHCP/identity).
: > /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id 2>/dev/null || true

# SSH host keys regenerate on next boot (avoids cloned hosts sharing keys).
rm -f /etc/ssh/ssh_host_* 2>/dev/null || true

# cloud-init (if present) -- reset so it re-runs cleanly on the clone.
if command -v cloud-init >/dev/null 2>&1; then
    cloud-init clean --logs >/dev/null 2>&1 || true
fi

# Clear logs and shell history.
find /var/log -type f -exec truncate -s 0 {} + 2>/dev/null || true
rm -f /root/.bash_history 2>/dev/null || true
for home in /home/*; do
    [ -d "$home" ] && rm -f "$home/.bash_history" 2>/dev/null || true
done

echo "===== firstboot-setup complete ($DISTRO) ====="
echo "Runner : $RUNNER"
echo "Unit   : $UNIT (enabled)"
echo "Next   : snapshot/export this image as your golden image."

if [ "$SHUTDOWN" -eq 1 ]; then
    echo "Shutting down ..."
    sync
    systemctl poweroff
else
    echo "Leaving VM running (--no-shutdown). Power it off when ready."
fi
