#!/usr/bin/env bash
#
# firstboot-setup.sh -- Prepare a Linux golden image for per-VM first-boot config.
#
# The Linux analogue of base-vm-setup/windows-server/firstboot-sysprep.ps1. Run
# this ONCE on the golden image, as root, as the last step before you snapshot /
# export it. It:
#
#   1. Installs a generic first-boot RUNNER (/usr/local/sbin/firstboot-runner.sh)
#      and a systemd one-shot unit (firstboot.service) that invokes it on the
#      next boot of a deployed VM.
#   2. Ensures systemd-networkd is enabled. The per-VM network script targets one
#      stack, chosen with `gen-network --backend`; both of the ones this image can
#      run (netplan's default `renderer: networkd`, and systemd-networkd directly)
#      need systemd-networkd up.
#   3. "Generalizes" the image (the sysprep-generalize analogue): resets the
#      machine-id, removes SSH host keys, clears logs and shell history, so each
#      deployed clone gets a fresh identity.
#
# On a deployed VM the runner locates the config disc by a firstboot.manifest at
# the root of a mounted ISO (the manifest isokit writes; see the pack-iso CLI),
# stages any payload files a v2 manifest lists, runs the scripts it lists -- in
# order, as root -- then owns the single reboot. Run is fail-fast: if any script
# exits non-zero, the runner logs it, writes /var/log/firstboot-error.log, and
# does NOT reboot.
#
# The config disc is produced by the pack-iso CLI (isokit) from per-VM scripts
# generated by configgen (gen-hostname / gen-network).
#
# Usage:
#   sudo ./firstboot-setup.sh                 # generalize, then power off
#   sudo ./firstboot-setup.sh --no-shutdown   # leave the VM running
set -euo pipefail

SHUTDOWN=1

usage() {
    echo "Usage: $0 [--no-shutdown]" >&2
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --no-shutdown) SHUTDOWN=0; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root." >&2
    exit 1
fi

# Informational only -- nothing below branches on the distro.
DISTRO="$( . /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-$ID}" )"
DISTRO="${DISTRO:-unknown}"

echo "===== firstboot-setup ($DISTRO) ====="

RUNNER=/usr/local/sbin/firstboot-runner.sh
UNIT=/etc/systemd/system/firstboot.service

# The interface name a clone of this image will come up with. vmkit's VMX
# template pins ethernet0.pciSlotNumber = "33", and on VMware the predictable
# name derives from that slot, so every VM clone-vm produces is ens33. An image
# built at a different slot is named differently from its own clones -- harmless
# for generated configs (the per-VM script detects the NIC at runtime) but a trap
# for anything baked into the image that names an interface.
CLONE_IFACE=ens33

# ---------------------------------------------------------------------------
# 1. Install the first-boot runner
# ---------------------------------------------------------------------------
# The runner is a real sibling file (single source of truth, testable against
# a fake disc dir) rather than an embedded heredoc. Copy the whole
# linux-server/ folder to the VM, not just this script.

echo "Installing runner: $RUNNER"
runner_src="$(cd "$(dirname "$0")" && pwd)/firstboot-runner.sh"
[ -f "$runner_src" ] || { echo "ERROR: firstboot-runner.sh not found next to this script ($runner_src). Copy the whole linux-server/ folder to the VM." >&2; exit 1; }
grep -q 'FIRSTBOOT-RUNNER-MARKER' "$runner_src" || { echo "ERROR: $runner_src does not look like the first-boot runner (marker missing)." >&2; exit 1; }
install -m 0755 "$runner_src" "$RUNNER"

# The runner parses firstboot.manifest with python3 -- surface a missing
# interpreter at image-build time, not on first boot of a deployed clone.
command -v python3 >/dev/null 2>&1 || \
    echo "WARN: python3 not found -- the first-boot runner requires it to parse firstboot.manifest."

# ---------------------------------------------------------------------------
# 2. Install the systemd one-shot unit
# ---------------------------------------------------------------------------
echo "Installing unit: $UNIT"
cat > "$UNIT" <<UNIT
[Unit]
Description=First-boot per-VM configuration runner
After=network-pre.target systemd-networkd.service local-fs.target
Wants=network-pre.target
# Skip once the runner has succeeded (it also disables itself).
ConditionPathExists=!/var/lib/firstboot/done

[Service]
Type=oneshot
ExecStart=$RUNNER
RemainAfterExit=no
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable firstboot.service
echo "Enabled firstboot.service (runs on next boot)."

# ---------------------------------------------------------------------------
# 3. Ensure systemd-networkd (+ resolved for DNS=) are enabled
# ---------------------------------------------------------------------------
# netplan renders to systemd-networkd by default, so this is required whether the
# per-VM script is generated with --backend netplan or systemd-networkd.
echo "Enabling systemd-networkd ..."
systemctl enable systemd-networkd >/dev/null 2>&1 || \
    echo "WARN: could not enable systemd-networkd -- ensure the base image provides it."
# systemd-resolved makes the .network DNS= directives take effect via resolv.conf.
systemctl enable systemd-resolved >/dev/null 2>&1 || \
    echo "WARN: systemd-resolved not enabled -- DNS= in .network may not apply."

# ---------------------------------------------------------------------------
# 4. Generalize the image (run last, just before snapshot/export)
# ---------------------------------------------------------------------------
echo "Generalizing image ..."

# Fresh machine-id per clone (duplicate IDs break systemd-networkd DHCP/identity).
: > /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id 2>/dev/null || true

# SSH host keys regenerate on next boot (avoids cloned hosts sharing keys).
rm -f /etc/ssh/ssh_host_* 2>/dev/null || true

# cloud-init (if present) -- reset so it re-runs cleanly on the clone.
#
# --configs network additionally drops the network config cloud-init rendered at
# install time (/etc/netplan/50-cloud-init.yaml). That file names THIS VM's
# interface, which is derived from its ethernet0.pciSlotNumber -- clones get the
# slot vmkit's VMX template pins, so the name usually differs (ens34 here, ens33
# on the clone). Left behind, the file rides into every clone describing a link
# that does not exist there: inert until a slot change makes it live, at which
# point it claims the golden image's address on a deployed VM. A plain
# `cloud-init clean` does not remove it.
if command -v cloud-init >/dev/null 2>&1; then
    # --configs landed in cloud-init 23.1; fall back for older images.
    cloud-init clean --logs --configs network >/dev/null 2>&1 || \
        cloud-init clean --logs >/dev/null 2>&1 || true
fi
# Belt and braces: remove it directly, covering both the pre-23.1 fallback above
# and an image where cloud-init is absent but its rendered config is not.
if [ -e /etc/netplan/50-cloud-init.yaml ]; then
    rm -f /etc/netplan/50-cloud-init.yaml
    echo "Removed stale /etc/netplan/50-cloud-init.yaml (named this image's NIC)."
fi

# Clear logs and shell history.
find /var/log -type f -exec truncate -s 0 {} + 2>/dev/null || true
rm -f /root/.bash_history 2>/dev/null || true
for home in /home/*; do
    [ -d "$home" ] && rm -f "$home/.bash_history" 2>/dev/null || true
done

echo "===== firstboot-setup complete ($DISTRO) ====="
echo "Runner : $RUNNER"
echo "Unit   : $UNIT (enabled)"

# Any netplan config left here is one the operator wrote, so it is not ours to
# delete -- but if it names an interface it will carry that name into clones the
# same way 50-cloud-init.yaml did. The netplan backend moves these aside on the
# clone; the systemd-networkd backend does not.
remaining=$(ls /etc/netplan/*.yaml /etc/netplan/*.yml 2>/dev/null || true)
if [ -n "$remaining" ]; then
    echo "WARN   : netplan config remains in this image:"
    printf '           %s\n' $remaining
    echo "           Check it does not pin an interface name -- clones get the NIC at the"
    echo "           PCI slot vmkit's VMX pins, which may not match this VM's."
fi

# Same detection the generated per-VM network script uses: first physical,
# non-loopback link.
image_iface=""
for cand in /sys/class/net/*; do
    name=$(basename "$cand")
    [ "$name" = lo ] && continue
    [ -e "$cand/device" ] || continue
    image_iface=$name
    break
done
if [ -z "$image_iface" ]; then
    echo "WARN   : no physical network interface found; cannot check this image's NIC name."
elif [ "$image_iface" != "$CLONE_IFACE" ]; then
    echo "WARN   : this image's NIC is '$image_iface', but clones of it will be '$CLONE_IFACE'"
    echo "           (clone-vm pins ethernet0.pciSlotNumber=33). Generated configs are"
    echo "           unaffected -- they detect the NIC at runtime -- but anything baked"
    echo "           into this image naming '$image_iface' will not match on a clone."
    echo "           To align them, move this VM's NIC to PCI slot 33 and rebake."
fi

echo "Next   : snapshot/export this image as your golden image."
echo "         This image now has NO network config of its own. If you boot it again"
echo "         to update it, configure the NIC by hand first."

if [ "$SHUTDOWN" -eq 1 ]; then
    echo "Shutting down ..."
    sync
    systemctl poweroff
else
    echo "Leaving VM running (--no-shutdown). Power it off when ready."
fi
