#!/usr/bin/env python3
"""
hostname.py — Generate the per-VM hostname first-boot script.

Emits a PowerShell script that, on first boot, sets the machine hostname — the
rename logic that used to live alongside the network config inside
gen_network_script.py. The value is validated here (generation time) and baked
into the script as a `$cfg` hashtable. The script does NOT reboot: FirstBoot.ps1
(the runner) owns the single reboot after all scripts succeed.

This tool only writes the .ps1. Pack it into a config ISO with
pack_scripts_into_iso.py, which also writes the firstboot.manifest the runner
uses to find the disc:

  ./script-generators/windows-server/hostname.py -n dc01 -o 10-hostname.ps1
  ./pack_scripts_into_iso.py 10-hostname.ps1 20-network.ps1 -o isos/dc01-config.iso
"""

import argparse
import sys
from pathlib import Path

# These generators live two levels below the project root; put the root on the
# import path so `vmlib` resolves no matter the current working directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from vmlib.validate import validate_hostname_rfc  # noqa: E402

DEFAULT_SCRIPT_NAME = "10-hostname.ps1"


def _ps_literal(value: str) -> str:
    """Render a Python string as a PowerShell single-quoted literal (escape ')."""
    return "'" + str(value).replace("'", "''") + "'"


def _build_cfg_block(args: argparse.Namespace) -> str:
    lines = [f"    hostname = {_ps_literal(args.hostname)}"]
    return "$cfg = @{\n" + "\n".join(lines) + "\n}"


# The apply-logic below is ported verbatim from the original FirstBoot.ps1
# hostname section. Progress goes to stdout (the runner captures it into
# firstboot.log); failures throw, which exits non-zero so the runner fails fast.
_SCRIPT_TEMPLATE = """\
<#
.SYNOPSIS
    Per-VM hostname first-boot configuration. Generated by
    hostname.py -- do not hand-edit.

.DESCRIPTION
    Spawned as SYSTEM by FirstBoot.ps1 (the runner) in its own child process.
    Stages the machine hostname, then exits. It does NOT reboot -- the runner
    owns the single reboot after all scripts succeed. Progress is written to
    stdout (captured by the runner into C:\\Windows\\Temp\\firstboot.log); any
    failure throws and exits non-zero.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Config (baked in by the generator; values are pre-validated) ----------
{cfg_block}

$hostname = $cfg.hostname.Trim()

# --- Lightweight runtime guard (defense vs corrupt/hand-edited ISO) --------
if ($hostname.Length -gt 15) {{ Write-Output "WARN: Hostname '$hostname' exceeds 15 chars -- NetBIOS name will be truncated." }}

Write-Output "hostname: hostname=$hostname"

# --- Apply hostname --------------------------------------------------------

# NetBIOS computer name: max 15 chars, stored upper-case.
$netbiosName = $hostname
if ($netbiosName.Length -gt 15) {{ $netbiosName = $netbiosName.Substring(0, 15) }}
$netbiosName = $netbiosName.ToUpper()

if ($env:COMPUTERNAME -eq $netbiosName) {{
    Write-Output "hostname: hostname is already '$hostname' -- skipping rename."
}} else {{
    # Rename-Computer is unreliable in this context: running as SYSTEM with no
    # logon session it can report success without persisting the pending name.
    # Try it, then VERIFY the pending name landed in the registry; if it did
    # not, write the name directly to the keys Windows reads at boot.
    try {{
        Rename-Computer -NewName $hostname -Force -ErrorAction Stop
        Write-Output "hostname: Rename-Computer invoked for '$hostname'."
    }} catch {{
        Write-Output "WARN: Rename-Computer failed: $($_.Exception.Message). Falling back to registry."
    }}

    $pendingKey = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\ComputerName\\ComputerName'
    $tcpipKey   = 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters'

    $pendingName = (Get-ItemProperty -Path $pendingKey).ComputerName
    if ($pendingName -ne $netbiosName) {{
        Set-ItemProperty -Path $pendingKey -Name 'ComputerName' -Value $netbiosName
        Set-ItemProperty -Path $tcpipKey   -Name 'Hostname'     -Value $hostname
        Set-ItemProperty -Path $tcpipKey   -Name 'NV Hostname'  -Value $hostname
        Write-Output "hostname: hostname staged via registry ('$pendingName' -> '$netbiosName'); reboot applies it."
    }} else {{
        Write-Output "hostname: hostname staged via Rename-Computer ('$pendingName'); reboot applies it."
    }}
}}

Write-Output "hostname: configuration applied (no reboot -- runner owns it)."
"""


def render_hostname_script(args: argparse.Namespace) -> str:
    return _SCRIPT_TEMPLATE.format(cfg_block=_build_cfg_block(args))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hostname.py",
        description=(
            "Generate the per-VM hostname first-boot script (a .ps1).\n"
            "Pack it into a config ISO with pack_scripts_into_iso.py. FirstBoot.ps1\n"
            "runs it as SYSTEM on first boot to stage the machine hostname."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  %(prog)s -n dc01 -o 10-hostname.ps1\n"
            "  ./pack_scripts_into_iso.py 10-hostname.ps1 20-network.ps1 "
            "-o isos/dc01-config.iso"
        ),
    )
    parser.add_argument(
        "-n", "--hostname", required=True, type=validate_hostname_rfc,
        metavar="HOSTNAME", help="VM hostname (RFC 1123).",
    )
    parser.add_argument(
        "-o", "--output", default=DEFAULT_SCRIPT_NAME,
        metavar="FILE",
        help=f"Output .ps1 path. Defaults to {DEFAULT_SCRIPT_NAME} in the current directory.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_hostname_script(args), encoding="utf-8")

    print(f"Script written to: {output_path}")
    print(f"  hostname    = {args.hostname}")
    print("\nNext: pack it into an ISO with")
    print(f"  ./pack_scripts_into_iso.py {output_path} -o isos/{args.hostname}-config.iso")


if __name__ == "__main__":
    main()
