#!/usr/bin/env python3
"""
network.py — Generate the per-VM network first-boot script.

Emits a PowerShell script that, on first boot, configures the primary network
adapter — either a static IP (address, subnet prefix, gateway, DNS) or DHCP.
The values are validated here (generation time) and baked into the script as a
`$cfg` hashtable. The script does NOT reboot: FirstBoot.ps1 (the runner) owns
the single reboot after all scripts succeed. Hostname is configured separately
by hostname.py.

This tool only writes the .ps1. Pack it into a config ISO with
pack_scripts_into_iso.py, which also writes the firstboot.manifest the runner
uses to find the disc:

  # static
  ./script-generators/windows-server/network.py --ip 192.168.1.50 --prefix 24 \\
      --gateway 192.168.1.1 --dns1 192.168.1.10 -o 20-network.ps1
  # dhcp
  ./script-generators/windows-server/network.py --dhcp -o 20-network.ps1
  ./pack_scripts_into_iso.py 10-hostname.ps1 20-network.ps1 -o isos/dc01-config.iso
"""

import argparse
import sys
from pathlib import Path

# These generators live two levels below the project root; put the root on the
# import path so `vmlib` resolves no matter the current working directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from vmlib.validate import validate_ipv4, validate_prefix  # noqa: E402

DEFAULT_SCRIPT_NAME = "20-network.ps1"


def _ps_literal(value: str) -> str:
    """Render a Python string as a PowerShell single-quoted literal (escape ')."""
    return "'" + str(value).replace("'", "''") + "'"


def _build_cfg_block(args: argparse.Namespace) -> str:
    mode = "dhcp" if args.dhcp else "static"
    lines = [f"    mode       = {_ps_literal(mode)}"]
    if not args.dhcp:
        lines += [
            f"    ip         = {_ps_literal(args.ip)}",
            f"    prefix     = {int(args.prefix)}",
            f"    gateway    = {_ps_literal(args.gateway)}",
        ]
    # DNS is optional in DHCP mode (falls back to DHCP-provided servers) and
    # required in static mode (enforced at parse time).
    if args.dns1 is not None:
        lines.append(f"    dns1       = {_ps_literal(args.dns1)}")
    if args.dns2 is not None:
        lines.append(f"    dns2       = {_ps_literal(args.dns2)}")
    if args.dns_suffix is not None:
        lines.append(f"    dns_suffix = {_ps_literal(args.dns_suffix)}")
    return "$cfg = @{\n" + "\n".join(lines) + "\n}"


# The apply-logic below is ported from the original FirstBoot.ps1 network
# section, with a DHCP branch added. Progress goes to stdout (the runner
# captures it into firstboot.log); failures throw, which exits non-zero so the
# runner fails fast.
_SCRIPT_TEMPLATE = """\
<#
.SYNOPSIS
    Per-VM network first-boot configuration. Generated by network.py -- do not
    hand-edit.

.DESCRIPTION
    Spawned as SYSTEM by FirstBoot.ps1 (the runner) in its own child process.
    Configures the primary network adapter for either a static IP (address,
    subnet prefix, gateway, DNS) or DHCP, then exits. It does NOT reboot -- the
    runner owns the single reboot after all scripts succeed. Progress is written
    to stdout (captured by the runner into C:\\Windows\\Temp\\firstboot.log); any
    failure throws and exits non-zero.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Config (baked in by the generator; values are pre-validated) ----------
{cfg_block}

$mode      = $cfg.mode.Trim().ToLower()
$ip        = if ($cfg.ContainsKey('ip'))         {{ ([string]$cfg.ip).Trim() }}         else {{ $null }}
$prefix    = if ($cfg.ContainsKey('prefix'))     {{ [int]$cfg.prefix }}                 else {{ $null }}
$gateway   = if ($cfg.ContainsKey('gateway'))    {{ ([string]$cfg.gateway).Trim() }}    else {{ $null }}
$dns1      = if ($cfg.ContainsKey('dns1'))       {{ ([string]$cfg.dns1).Trim() }}       else {{ $null }}
$dns2      = if ($cfg.ContainsKey('dns2'))       {{ ([string]$cfg.dns2).Trim() }}       else {{ $null }}
$dnsSuffix = if ($cfg.ContainsKey('dns_suffix')) {{ ([string]$cfg.dns_suffix).Trim() }} else {{ $null }}

# --- Lightweight runtime guard (defense vs corrupt/hand-edited ISO) --------
$ipRegex = '^\\d{{1,3}}(\\.\\d{{1,3}}){{3}}$'
if ($mode -ne 'static' -and $mode -ne 'dhcp') {{ throw "Unknown network mode '$mode' (expected 'static' or 'dhcp')." }}
if ($mode -eq 'static') {{
    foreach ($field in @($ip, $gateway, $dns1)) {{
        if ($field -notmatch $ipRegex) {{ throw "Value '$field' does not look like a valid IPv4 address." }}
    }}
    if ($prefix -lt 1 -or $prefix -gt 32) {{ throw "Prefix '$prefix' is out of range (1-32)." }}
}}
foreach ($dns in @($dns1, $dns2)) {{
    if ($dns -and $dns -notmatch $ipRegex) {{ throw "DNS value '$dns' does not look like a valid IPv4 address." }}
}}

Write-Output "network: mode=$mode ip=$ip prefix=$prefix gateway=$gateway dns1=$dns1 dns2=$dns2 dns_suffix=$dnsSuffix"

# --- Find the adapter ------------------------------------------------------

# Find the first connected physical adapter -- skip loopback/tunnels
$nic = Get-NetAdapter |
    Where-Object {{ $_.Status -eq 'Up' -and $_.InterfaceDescription -notmatch 'Loopback|Hyper-V|isatap|Teredo' }} |
    Sort-Object -Property ifIndex |
    Select-Object -First 1

if (-not $nic) {{
    throw "No active network adapter found. Cannot configure network."
}}

Write-Output "network: using adapter $($nic.Name) ($($nic.InterfaceDescription))"

# Remove existing IP configuration on this adapter
Remove-NetIPAddress -InterfaceIndex $nic.ifIndex -Confirm:$false -ErrorAction SilentlyContinue
Remove-NetRoute     -InterfaceIndex $nic.ifIndex -Confirm:$false -ErrorAction SilentlyContinue

if ($mode -eq 'dhcp') {{
    # --- Configure DHCP ----------------------------------------------------
    Set-NetIPInterface -InterfaceIndex $nic.ifIndex -Dhcp Enabled
    Write-Output "network: DHCP enabled on $($nic.Name)"

    if ($dns1) {{
        # Static DNS override on top of a DHCP address.
        $dnsServers = @($dns1)
        if ($dns2) {{ $dnsServers += $dns2 }}
        Set-DnsClientServerAddress -InterfaceIndex $nic.ifIndex -ServerAddresses $dnsServers
        Write-Output "network: DNS servers set $($dnsServers -join ', ') (static override)"
    }} else {{
        # Take DNS from DHCP as well.
        Set-DnsClientServerAddress -InterfaceIndex $nic.ifIndex -ResetServerAddresses
        Write-Output "network: DNS servers from DHCP"
    }}
}} else {{
    # --- Configure static IP -----------------------------------------------
    New-NetIPAddress `
        -InterfaceIndex  $nic.ifIndex `
        -IPAddress       $ip `
        -PrefixLength    $prefix `
        -DefaultGateway  $gateway | Out-Null

    Write-Output "network: IP address set $ip/$prefix via $gateway"

    $dnsServers = @($dns1)
    if ($dns2) {{ $dnsServers += $dns2 }}
    Set-DnsClientServerAddress -InterfaceIndex $nic.ifIndex -ServerAddresses $dnsServers
    Write-Output "network: DNS servers set $($dnsServers -join ', ')"
}}

# Set DNS search suffix if provided
if ($dnsSuffix) {{
    Set-DnsClient -InterfaceIndex $nic.ifIndex -ConnectionSpecificSuffix $dnsSuffix
    Write-Output "network: DNS suffix set $dnsSuffix"
}}

Write-Output "network: configuration applied (no reboot -- runner owns it)."
"""


def render_network_script(args: argparse.Namespace) -> str:
    return _SCRIPT_TEMPLATE.format(cfg_block=_build_cfg_block(args))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="network.py",
        description=(
            "Generate the per-VM network first-boot script (a .ps1).\n"
            "Configures the primary adapter for a static IP or DHCP. Pack it into\n"
            "a config ISO with pack_scripts_into_iso.py. FirstBoot.ps1 runs it as\n"
            "SYSTEM on first boot."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  %(prog)s --ip 192.168.1.50 --prefix 24 "
            "--gateway 192.168.1.1 --dns1 192.168.1.10 -o 20-network.ps1\n"
            "  %(prog)s --dhcp -o 20-network.ps1\n"
            "  %(prog)s --dhcp --dns1 192.168.1.10 --dns-suffix corp.example.com "
            "-o 20-network.ps1\n"
            "  ./pack_scripts_into_iso.py 10-hostname.ps1 20-network.ps1 "
            "-o isos/dc01-config.iso"
        ),
    )
    parser.add_argument(
        "--dhcp", action="store_true",
        help="Configure the adapter via DHCP instead of a static IP. "
             "Makes --ip/--prefix/--gateway irrelevant and --dns1 optional.",
    )
    parser.add_argument(
        "--ip", type=validate_ipv4,
        metavar="ADDR", help="Static IPv4 address (dotted-quad). Required unless --dhcp.",
    )
    parser.add_argument(
        "--prefix", type=validate_prefix,
        metavar="LEN", help="Subnet prefix length (1-32). Required unless --dhcp.",
    )
    parser.add_argument(
        "--gateway", type=validate_ipv4,
        metavar="ADDR", help="Default gateway IPv4 address. Required unless --dhcp.",
    )
    parser.add_argument(
        "--dns1", default=None, type=validate_ipv4,
        metavar="ADDR", help="Primary DNS server IPv4 address. "
                             "Required for static; optional override for DHCP.",
    )
    parser.add_argument(
        "--dns2", default=None, type=validate_ipv4,
        metavar="ADDR", help="Secondary DNS server IPv4 address (optional).",
    )
    parser.add_argument(
        "--dns-suffix", default=None,
        metavar="SUFFIX", help="DNS search suffix, e.g. corp.example.com (optional).",
    )
    parser.add_argument(
        "-o", "--output", default=DEFAULT_SCRIPT_NAME,
        metavar="FILE",
        help=f"Output .ps1 path. Defaults to {DEFAULT_SCRIPT_NAME} in the current directory.",
    )
    return parser


def _validate_args(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    """Enforce the static/DHCP argument contract argparse can't express directly."""
    if args.dhcp:
        conflicting = [
            name for name, val in (("--ip", args.ip), ("--prefix", args.prefix),
                                    ("--gateway", args.gateway))
            if val is not None
        ]
        if conflicting:
            parser.error(f"{', '.join(conflicting)} cannot be used with --dhcp.")
        if args.dns2 is not None and args.dns1 is None:
            parser.error("--dns2 requires --dns1.")
    else:
        missing = [
            name for name, val in (("--ip", args.ip), ("--prefix", args.prefix),
                                    ("--gateway", args.gateway), ("--dns1", args.dns1))
            if val is None
        ]
        if missing:
            parser.error(
                f"static mode requires {', '.join(missing)} (or pass --dhcp)."
            )


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    _validate_args(parser, args)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_network_script(args), encoding="utf-8")

    print(f"Script written to: {output_path}")
    if args.dhcp:
        print("  mode        = dhcp")
    else:
        print("  mode        = static")
        print(f"  ip/prefix   = {args.ip}/{args.prefix}")
        print(f"  gateway     = {args.gateway}")
    if args.dns1 is not None:
        print(f"  dns1        = {args.dns1}")
    if args.dns2 is not None:
        print(f"  dns2        = {args.dns2}")
    if args.dns_suffix is not None:
        print(f"  dns-suffix  = {args.dns_suffix}")
    print("\nNext: pack it into an ISO with")
    print(f"  ./pack_scripts_into_iso.py {output_path} -o isos/<hostname>-config.iso")


if __name__ == "__main__":
    main()
