<#
.SYNOPSIS
    First-boot script runner. Runs once via SetupComplete.cmd after Sysprep
    OOBE completes on a deployed golden-image VM.

    FIRSTBOOT-RUNNER-MARKER (firstboot-sysprep.ps1 verifies this before staging)

.DESCRIPTION
    Runs non-interactively as SYSTEM before any logon session exists, so
    nothing it could print would ever be seen. It therefore produces no
    console output; progress and errors are appended to
    C:\Windows\Temp\firstboot.log (fatal errors additionally to
    C:\Windows\Temp\firstboot-error.log).

    This is a generic RUNNER, not the configuration itself. It locates the
    config disc by a firstboot.manifest file at the root of a mounted ISO
    (the manifest is how the config disc is told apart from unrelated CD
    media such as VMware Tools or install ISOs), then runs the scripts the
    manifest lists, in order, each in its own child process as SYSTEM:
    .ps1 via powershell.exe, .cmd/.bat via cmd.exe. Scripts are staged to a
    local temp dir and Unblock-File'd first so RemoteSigned does not refuse
    to run them off the CD.

    Version-2 manifests may also carry a "files" list: arbitrary payload
    files (binaries welcome) that are never executed. They are staged to a
    files\ subdirectory of the work dir before any script runs; scripts find
    them via $env:FIRSTBOOT_FILES_DIR (also reachable as the relative path
    files\<name> -- scripts run with the work dir as their working
    directory). Staging is TRANSIENT: the finalize pass deletes the whole
    work dir, so a script that needs a payload to persist must install it
    (copy it to its final location) during first boot. Version-1 manifests
    (no "files" key) behave exactly as before.

    Run is fail-fast: if any script exits non-zero, the runner logs it, writes
    firstboot-error.log, and does NOT reboot. The RUNNER owns the single
    reboot -- individual scripts must never reboot. Only after every script
    succeeds does it register a one-shot FirstBootFinalize startup task and
    reboot; that task then removes the first-boot artifacts and performs one
    final automatic reboot, after which the new hostname is fully active.

    The config disc is produced by isokit (build_script_iso / build_config_iso;
    see the pack-iso CLI) from per-VM scripts generated by configgen.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$LogPath      = "$env:SystemRoot\Temp\firstboot.log"
$ErrorLogPath = "$env:SystemRoot\Temp\firstboot-error.log"

function Write-Log {
    param([string]$Message)
    Add-Content -Path $LogPath -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $Message"
}

function Get-ConfigDiscRoots {
    <#
        Candidate roots that might hold a firstboot.manifest. Normally every
        CD-ROM drive (DriveType 5). FIRSTBOOT_SEARCH_ROOTS (';'-separated
        directories) overrides the CD scan -- a unit-test hook only, never set
        on a real deployment.
    #>
    if ($env:FIRSTBOOT_SEARCH_ROOTS) {
        return @($env:FIRSTBOOT_SEARCH_ROOTS -split ';' | Where-Object { $_ })
    }
    @(Get-CimInstance Win32_LogicalDisk |
        Where-Object { $_.DriveType -eq 5 } |
        ForEach-Object { $_.DeviceID })
}

function Read-FirstBootManifest {
    <#
        Parse a firstboot.manifest into a normalized object. StrictMode-safe:
        version-1 manifests have no 'files' key, so every optional property is
        probed via PSObject.Properties before access. A non-empty 'scripts'
        list is required either way -- a scripts-empty disc would stage files
        into a work dir the finalize pass immediately deletes, so reject it
        loudly rather than reboot for nothing.
    #>
    param([string]$Path)

    $manifest = Get-Content -Path $Path -Raw -Encoding UTF8 | ConvertFrom-Json

    if (-not $manifest.PSObject.Properties['scripts'] -or -not $manifest.scripts) {
        throw "Manifest '$Path' has no non-empty 'scripts' list."
    }

    $version = if ($manifest.PSObject.Properties['version']) { $manifest.version } else { $null }
    $files   = if ($manifest.PSObject.Properties['files'] -and $manifest.files) { @($manifest.files) } else { @() }

    [pscustomobject]@{
        Version = $version
        Scripts = @($manifest.scripts)
        Files   = $files
    }
}

function Get-ScriptInvocation {
    <#
        Map a staged script to the process that runs it. Anything unsupported
        throws -- failing fast beats silently handing a batch file to
        powershell.exe -File (the pre-v2 behavior for every entry).
    #>
    param([string]$StagedPath)

    $ext = [IO.Path]::GetExtension($StagedPath).ToLowerInvariant()
    switch ($ext) {
        '.ps1' {
            @{
                FilePath     = 'powershell.exe'
                ArgumentList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-WindowStyle', 'Hidden', '-File', $StagedPath)
            }
        }
        { $_ -in @('.cmd', '.bat') } {
            # /d skips AutoRun registry commands; the path is quoted defensively.
            @{
                FilePath     = $env:ComSpec
                ArgumentList = @('/d', '/c', "`"$StagedPath`"")
            }
        }
        default {
            throw "Unsupported script type '$ext' for '$([IO.Path]::GetFileName($StagedPath))'. Supported: .ps1, .cmd, .bat."
        }
    }
}

# Dot-sourced for unit tests (Pester): expose the functions above, run nothing.
if ($MyInvocation.InvocationName -eq '.') { return }

Write-Log "===== FirstBoot starting (as $env:USERNAME on $env:COMPUTERNAME) ====="

try {

    # -----------------------------------------------------------------------
    # 1. Locate the config disc by its firstboot.manifest marker
    # -----------------------------------------------------------------------

    $manifestName  = "firstboot.manifest"
    $manifestFile  = $null
    $manifestDrive = $null
    $discRoots     = Get-ConfigDiscRoots

    foreach ($root in $discRoots) {
        $candidate = Join-Path $root $manifestName
        Write-Log "Scanning $root for $manifestName ..."
        if (Test-Path $candidate) {
            $manifestFile  = $candidate
            $manifestDrive = $root
            break
        }
    }

    if (-not $manifestFile) {
        throw "No config disc found. Checked: $($discRoots -join ', '). Ensure $manifestName is at the root of a mounted ISO."
    }

    Write-Log "Config disc: $manifestDrive (manifest: $manifestFile)"

    # -----------------------------------------------------------------------
    # 2. Parse the manifest (scripts to run, payload files to stage)
    # -----------------------------------------------------------------------

    $manifest = Read-FirstBootManifest -Path $manifestFile

    $versionLabel = if ($null -ne $manifest.Version) { $manifest.Version } else { '(unset)' }
    if (($manifest.Version -as [int]) -gt 2) {
        Write-Log "WARN: manifest version $versionLabel is newer than supported (2); proceeding with the known keys."
    }
    Write-Log "Manifest version $versionLabel; $($manifest.Scripts.Count) script(s) in order: $($manifest.Scripts -join ', ')"
    if ($manifest.Files.Count -gt 0) {
        Write-Log "$($manifest.Files.Count) payload file(s): $($manifest.Files -join ', ')"
    }

    # -----------------------------------------------------------------------
    # 3. Stage payload files, then scripts, locally
    # -----------------------------------------------------------------------

    # Why local copies: scripts on a CD carry the Mark-of-the-Web, so running
    # them in-place can trip RemoteSigned ("not digitally signed"). Copy to a
    # local dir, Unblock-File, then run with -ExecutionPolicy Bypass.
    # Why child processes: a script's throw/exit cannot kill this runner, and
    # the runner's Set-StrictMode / $ErrorActionPreference do not bleed in.
    # Fail-fast: the first non-zero exit aborts the run (no reboot).

    $workDir = Join-Path $env:SystemRoot "Temp\firstboot-scripts"
    if (Test-Path $workDir) { Remove-Item -Path $workDir -Recurse -Force -ErrorAction SilentlyContinue }
    New-Item -ItemType Directory -Path $workDir -Force | Out-Null

    # Payload files go under files\ before any script runs. Scripts reach them
    # via $env:FIRSTBOOT_FILES_DIR or the relative path files\<name>. The whole
    # work dir (payloads included) is deleted by the finalize pass -- scripts
    # must install anything that should persist.
    $filesDir = Join-Path $workDir 'files'
    if ($manifest.Files.Count -gt 0) {
        New-Item -ItemType Directory -Path $filesDir -Force | Out-Null
        foreach ($name in $manifest.Files) {
            $src = Join-Path $manifestDrive $name
            if (-not (Test-Path $src)) {
                throw "Manifest lists file '$name' but it is not present on the disc ($src)."
            }
            Copy-Item -Path $src -Destination (Join-Path $filesDir $name) -Force
            Unblock-File -Path (Join-Path $filesDir $name) -ErrorAction SilentlyContinue
            Write-Log "Staged payload file '$name'."
        }
    }
    $env:FIRSTBOOT_FILES_DIR = $filesDir   # inherited by every child process

    # -----------------------------------------------------------------------
    # 4. Run each script in an isolated child process
    # -----------------------------------------------------------------------

    foreach ($name in $manifest.Scripts) {
        $src = Join-Path $manifestDrive $name
        if (-not (Test-Path $src)) {
            throw "Manifest lists '$name' but it is not present on the disc ($src)."
        }

        $dst = Join-Path $workDir $name
        Copy-Item -Path $src -Destination $dst -Force
        Unblock-File -Path $dst -ErrorAction SilentlyContinue   # strip Mark-of-the-Web

        $invocation = Get-ScriptInvocation -StagedPath $dst
        $stdoutFile = "$dst.out"
        $stderrFile = "$dst.err"

        Write-Log "----- Running '$name' -----"
        $proc = Start-Process -FilePath $invocation.FilePath `
            -ArgumentList $invocation.ArgumentList `
            -WorkingDirectory $workDir `
            -RedirectStandardOutput $stdoutFile `
            -RedirectStandardError  $stderrFile `
            -Wait -PassThru

        # Fold the child's output into the unified first-boot log
        foreach ($line in @(Get-Content -Path $stdoutFile -ErrorAction SilentlyContinue)) {
            if ($line) { Write-Log "  [out] $line" }
        }
        foreach ($line in @(Get-Content -Path $stderrFile -ErrorAction SilentlyContinue)) {
            if ($line) { Write-Log "  [err] $line" }
        }

        if ($proc.ExitCode -ne 0) {
            throw "Script '$name' exited with code $($proc.ExitCode). Aborting first-boot run -- NOT rebooting."
        }
        Write-Log "----- '$name' completed (exit 0) -----"
    }

    Write-Log "All $($manifest.Scripts.Count) script(s) completed successfully."

    # -----------------------------------------------------------------------
    # 5. Stage finalize pass: cleanup + automatic second reboot
    # -----------------------------------------------------------------------

    # The reboot below applies the staged hostname, but the new name is not
    # fully active until one more restart. Automate that with a one-shot
    # SYSTEM task that fires at the next startup: it removes the first-boot
    # artifacts, deregisters itself, and reboots a final time. (Startup
    # trigger, not logon -- nobody logs on to a freshly deployed VM.)

    $selfDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
    $finalizePs1 = "$env:SystemRoot\Temp\FirstBootFinalize.ps1"

    $finalizeContent = @"
# One-shot finalize pass, registered by FirstBoot.ps1. Runs as SYSTEM at the
# first startup after first-boot configuration was applied.
if (-not (Test-Path '$selfDir\FirstBoot.ps1')) {
    # Artifacts already gone: finalize ran on an earlier boot. Never reboot
    # from here again -- just make sure the task is gone, then bail.
    Unregister-ScheduledTask -TaskName 'FirstBootFinalize' -Confirm:`$false -ErrorAction SilentlyContinue
    exit 0
}
Add-Content -Path '$LogPath' -Value "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  Finalize: hostname now '`$env:COMPUTERNAME'; cleaning up and performing final reboot."
Remove-Item -Path '$selfDir\FirstBoot.ps1'     -Force -ErrorAction SilentlyContinue
Remove-Item -Path '$selfDir\SetupComplete.cmd' -Force -ErrorAction SilentlyContinue
Remove-Item -Path "`$env:SystemRoot\Temp\firstboot-scripts" -Recurse -Force -ErrorAction SilentlyContinue
# Deregister BEFORE rebooting so this task cannot fire in a reboot loop.
Unregister-ScheduledTask -TaskName 'FirstBootFinalize' -Confirm:`$false -ErrorAction SilentlyContinue
Remove-Item -Path '$finalizePs1' -Force -ErrorAction SilentlyContinue
# Give the boot a moment to settle before restarting.
Start-Sleep -Seconds 15
Restart-Computer -Force
"@

    Set-Content -Path $finalizePs1 -Value $finalizeContent -Encoding UTF8

    $action    = New-ScheduledTaskAction -Execute 'powershell.exe' `
                     -Argument "-ExecutionPolicy RemoteSigned -WindowStyle Hidden -File `"$finalizePs1`""
    $trigger   = New-ScheduledTaskTrigger -AtStartup
    $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
    $settings  = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 5)
    Register-ScheduledTask -TaskName 'FirstBootFinalize' `
        -Action $action -Trigger $trigger -Principal $principal -Settings $settings `
        -Force | Out-Null

    Write-Log "Finalize task registered (next startup: cleanup + final reboot to fully activate hostname)."

    # -----------------------------------------------------------------------
    # 6. Reboot (finalize task reboots once more at next startup)
    # -----------------------------------------------------------------------

    Write-Log "Configuration complete -- rebooting."
    Restart-Computer -Force

} catch {

    $errMsg = $_.Exception.Message
    Write-Log "ERROR: First-boot configuration failed: $errMsg"

    # Separate error log so a failure is easy to spot
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$timestamp  ERROR: $errMsg`n$($_.ScriptStackTrace)" |
        Set-Content -Path $ErrorLogPath -Encoding UTF8 -Force

    Write-Log "Error details written to: $ErrorLogPath. Machine NOT rebooted."
    exit 1
}
